### ISSUE TITLE
Load glove

### ISSUE THREAD

**Issue by PratimaVK** [hans/glove.py#2]
How do I load the saved model (bin file)?

**Comment by hans** [comment]
The saved binary file is a pickled Numpy array (saved here: https://github.com/hans/glove.py/blob/master/glove.py#L357). If you're interested in reusing the model, you should definitely save the vocabulary as well. You can do this by including in the training invocation the option

```
--vocab-path <vocab-file>
```

A MessagePack vocabulary will be saved to this path.

You can then load the Numpy matrix + the vocabulary in order to perform word embedding lookups.
(Disclaimer—this system was never meant to be used in production and is only for learning purposes. You'll probably find more convenient / efficient GloVe implementations elsewhere..)
